
package ar.fiuba.redsocedu.datalayer.ws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "DataException", targetNamespace = "http://ws.datalayer.redsocedu.fiuba.ar/")
public class DataException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private DataExceptionBean faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public DataException(String message, DataExceptionBean faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public DataException(String message, DataExceptionBean faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: ar.fiuba.redsocedu.datalayer.ws.DataExceptionBean
     */
    public DataExceptionBean getFaultInfo() {
        return faultInfo;
    }

}
