
package ar.fiuba.redsocedu.datalayer.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IData", targetNamespace = "http://ws.datalayer.redsocedu.fiuba.ar/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IData {


    /**
     * 
     * @param transactionId
     * @param object
     * @param entityName
     */
    @WebMethod
    @RequestWrapper(localName = "delete", targetNamespace = "http://ws.datalayer.redsocedu.fiuba.ar/", className = "ar.fiuba.redsocedu.datalayer.ws.Delete")
    @ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://ws.datalayer.redsocedu.fiuba.ar/", className = "ar.fiuba.redsocedu.datalayer.ws.DeleteResponse")
    @Action(input = "http://ws.datalayer.redsocedu.fiuba.ar/IData/deleteRequest", output = "http://ws.datalayer.redsocedu.fiuba.ar/IData/deleteResponse")
    public void delete(
        @WebParam(name = "transactionId", targetNamespace = "")
        Long transactionId,
        @WebParam(name = "entityName", targetNamespace = "")
        String entityName,
        @WebParam(name = "object", targetNamespace = "")
        Object object);

    /**
     * 
     * @param transactionId
     * @param serializedCriteria
     * @return
     *     returns java.util.List<ar.fiuba.redsocedu.datalayer.ws.ReturnedObject>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "query", targetNamespace = "http://ws.datalayer.redsocedu.fiuba.ar/", className = "ar.fiuba.redsocedu.datalayer.ws.Query")
    @ResponseWrapper(localName = "queryResponse", targetNamespace = "http://ws.datalayer.redsocedu.fiuba.ar/", className = "ar.fiuba.redsocedu.datalayer.ws.QueryResponse")
    @Action(input = "http://ws.datalayer.redsocedu.fiuba.ar/IData/queryRequest", output = "http://ws.datalayer.redsocedu.fiuba.ar/IData/queryResponse")
    public List<ReturnedObject> query(
        @WebParam(name = "transactionId", targetNamespace = "")
        Long transactionId,
        @WebParam(name = "serializedCriteria", targetNamespace = "")
        String serializedCriteria);

    /**
     * 
     * @param transactionId
     */
    @WebMethod
    @RequestWrapper(localName = "commit", targetNamespace = "http://ws.datalayer.redsocedu.fiuba.ar/", className = "ar.fiuba.redsocedu.datalayer.ws.Commit")
    @ResponseWrapper(localName = "commitResponse", targetNamespace = "http://ws.datalayer.redsocedu.fiuba.ar/", className = "ar.fiuba.redsocedu.datalayer.ws.CommitResponse")
    @Action(input = "http://ws.datalayer.redsocedu.fiuba.ar/IData/commitRequest", output = "http://ws.datalayer.redsocedu.fiuba.ar/IData/commitResponse")
    public void commit(
        @WebParam(name = "transactionId", targetNamespace = "")
        Long transactionId);

    /**
     * 
     * @param transactionId
     */
    @WebMethod
    @RequestWrapper(localName = "beginTransaction", targetNamespace = "http://ws.datalayer.redsocedu.fiuba.ar/", className = "ar.fiuba.redsocedu.datalayer.ws.BeginTransaction")
    @ResponseWrapper(localName = "beginTransactionResponse", targetNamespace = "http://ws.datalayer.redsocedu.fiuba.ar/", className = "ar.fiuba.redsocedu.datalayer.ws.BeginTransactionResponse")
    @Action(input = "http://ws.datalayer.redsocedu.fiuba.ar/IData/beginTransactionRequest", output = "http://ws.datalayer.redsocedu.fiuba.ar/IData/beginTransactionResponse")
    public void beginTransaction(
        @WebParam(name = "transactionId", targetNamespace = "")
        Long transactionId);

    /**
     * 
     * @param transactionId
     * @param object
     * @param entityName
     * @return
     *     returns java.lang.Long
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "saveOrUpdate", targetNamespace = "http://ws.datalayer.redsocedu.fiuba.ar/", className = "ar.fiuba.redsocedu.datalayer.ws.SaveOrUpdate")
    @ResponseWrapper(localName = "saveOrUpdateResponse", targetNamespace = "http://ws.datalayer.redsocedu.fiuba.ar/", className = "ar.fiuba.redsocedu.datalayer.ws.SaveOrUpdateResponse")
    @Action(input = "http://ws.datalayer.redsocedu.fiuba.ar/IData/saveOrUpdateRequest", output = "http://ws.datalayer.redsocedu.fiuba.ar/IData/saveOrUpdateResponse")
    public Long saveOrUpdate(
        @WebParam(name = "transactionId", targetNamespace = "")
        Long transactionId,
        @WebParam(name = "entityName", targetNamespace = "")
        String entityName,
        @WebParam(name = "object", targetNamespace = "")
        Object object);

    /**
     * 
     * @param transactionId
     */
    @WebMethod
    @RequestWrapper(localName = "rollback", targetNamespace = "http://ws.datalayer.redsocedu.fiuba.ar/", className = "ar.fiuba.redsocedu.datalayer.ws.Rollback")
    @ResponseWrapper(localName = "rollbackResponse", targetNamespace = "http://ws.datalayer.redsocedu.fiuba.ar/", className = "ar.fiuba.redsocedu.datalayer.ws.RollbackResponse")
    @Action(input = "http://ws.datalayer.redsocedu.fiuba.ar/IData/rollbackRequest", output = "http://ws.datalayer.redsocedu.fiuba.ar/IData/rollbackResponse")
    public void rollback(
        @WebParam(name = "transactionId", targetNamespace = "")
        Long transactionId);

}
